#192.168.1.164
spring:
  application:
    name: itoken-config-8888
  boot:
    admin:
      client:
        url: http://192.168.1.164:8084
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/portnew/itoken.git
          search-paths: itoken-config-8888/respo #配置文件的保存位置
          username: 865383353@qq.com
          password: zhy13816995497
  zipkin:
    base-url: http://192.168.1.164:9411

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.164:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
