spring:
  application:
    name: itoken-admin-8084
  zipkin:
    base-url: http://192.168.1.164:9411

server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.164:8761/eureka/,http://192.168.1.164:8861/eureka/,http://192.168.1.164:8961/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info