spring:
  application:
    name: itoken-zipkin-9411
  boot:
    admin:
      client:
        url: http://itoken-zipkin-dev.yml:8084
  zipkin:
    base-url: http://itoken-zipkin-dev.yml:9411
#  main:
#    allow-bean-definition-overriding: true

server:
  port: 9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.164:8761/eureka/,http://192.168.1.164:8861/eureka/,http://192.168.1.164:8961/eureka/
  instance:
    instance-id: zipkin-9411
    prefer-ip-address: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
  metrics:
    web:
      server:
        auto-time-requests: false