server:
  port: 8761

spring:
  application:
    name: eureka
  boot:
    admin:
      client:
        url: http://192.168.1.164:8084
  zipkin:
    base-url: http://192.168.1.164:9411

eureka:
  instance:
    hostname: 192.168.1.164
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.1.164:8761/eureka/,http://192.168.1.164:8861/eureka/,http://192.168.1.164:8961/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info