spring:
  application:
    name: itoken-service-redis
  boot:
    admin:
      client:
        url: http://localhost:8084
  zipkin:
    base-url: http://localhost:9411
  redis:
#    host: 192.168.1.164
#    port: 7777
    cluster:
      nodes: 192.168.1.164:6379,192.168.1.164:6380,192.168.1.164:6381
      max-redirects: 3
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
#    sentinel:
#      master: mymaster
#      nodes: 192.168.75.140:26379

server:
  port: 8502

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info